

Echo comp1-time1-EventType1 9/29 – 11:49 am to 9/29 – 5pm  >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=1 and TimeGenerated BETWEEN TO_TIMESTAMP('09/29/2010 11:49', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/29/2010 17:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt

Echo comp1-time1-EventType2 9/29 – 11:49 am to 9/29 – 5pm >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=2 and TimeGenerated BETWEEN TO_TIMESTAMP('09/29/2010 11:49', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/29/2010 17:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt

Echo comp1-time2-EventType1 9/28 – 11:49 am to 9/28 – 5pm >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=1 and TimeGenerated BETWEEN TO_TIMESTAMP('09/28/2010 11:49', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/28/2010 17:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt

Echo comp1-time2-EventType2 9/28 – 11:49 am to 9/28 – 5pm >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=2 and TimeGenerated BETWEEN TO_TIMESTAMP('09/28/2010 11:49', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/28/2010 17:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt



Echo comp2-time1-EventType1 9/28 – 5pm to 9/29 – 11 am   >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=1 and TimeGenerated BETWEEN TO_TIMESTAMP('09/28/2010 17:00', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/29/2010 11:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt

Echo comp2-time1-EventType2 9/28 – 5pm to 9/29 – 11 am  >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=2 and TimeGenerated BETWEEN TO_TIMESTAMP('09/28/2010 17:00', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/29/2010 11:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt

Echo comp2-time2-EventType1 9/29 -5 pm to 9/30 – 11 am >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=1 and TimeGenerated BETWEEN TO_TIMESTAMP('09/29/2010 17:00', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/30/2010 11:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt

Echo comp2-time2-EventType2 9/29 -5 pm to 9/30 – 11 am >>c:\output.txt
"C:\Progra~1\Log Parser 2.2\LogParser" -i:EVT -e:NAT "SELECT Count(*) FROM \\PNYCPSRCHRES01\Application,\\PNYCPSRCHRES02\Application,\\PNYCPSRCHRES03\Application,\\PNYCPSRCHRES04\Application,\\PNYCPSRCHRES05\Application,\\PNYCPSRCHRES06\Application,\\PNYCPSRCHRES07\Application,\\PNJCPSRCHRES01\Application,\\PNJCPSRCHRES02\Application,\\PNJCPSRCHRES03\Application,\\PNJCPSRCHRES04\Application,\\PNJCPSRCHRES05\Application,\\PNJCPSRCHRES06\Application,\\PNJCPSRCHRES07\Application WHERE EventID=8534 and EventType=2 and TimeGenerated BETWEEN TO_TIMESTAMP('09/29/2010 17:00', 'MM/dd/yyyy hh:mm') AND TO_TIMESTAMP('09/30/2010 11:00', 'MM/dd/yyyy hh:mm')" -stats:OFF -q:ON >> C:\output.txt